### ISSUE TITLE
Getting below error in textbelt text.js

### ISSUE THREAD

**Issue by pravinsakthivel** [typpo/textbelt#109]
Error: write EPIPE
    at exports._errnoException (util.js:873:11)
    at Socket._writeGeneric (net.js:697:26)
    at Socket._write (net.js:716:8)
    at doWrite (_stream_writable.js:300:12)
    at writeOrBuffer (_stream_writable.js:286:5)
    at Socket.Writable.write (_stream_writable.js:214:11)
    at Socket.write (net.js:642:40)
    at C:\node_modules\express\node_modules\textbelt\text.js:83:17
    at Array.forEach (native)
    at Object.module.exports.sendText (C:\node_modules\express\node_modules\text
belt\text.js:58:18)

**Comment by pgibler** [comment]
This cannot run on windows because it relies on postfix, a unix e-mail application, to send text forwarding e-mails to the known endpoints. I run it on Ubuntu myself.

**Comment by daluu** [comment]
For those that must run on Windows, suggestion would be to use docker or a VM/vagrant.
