### ISSUE TITLE
Unable To Start Standalone Server

### ISSUE THREAD

**Issue by ksgithubapp** [typpo/textbelt#115]
/etc/textbelt/textbelt-master/lib/text.js:78
  config = Object.assign(config, obj);
                  ^
TypeError: Object function Object() { [native code] } has no method 'assign'
    at Object.setConfig [as config] (/etc/textbelt/textbelt-master/lib/text.js:78:19)
    at Object.<anonymous> (/etc/textbelt/textbelt-master/server/app.js:30:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by typpo** [comment]
It seems like you're using an older version of node without es6 support.  Can you let me know what version you're running `node --version`?

You should upgrade node or use an [object.assign polyfill](https://www.npmjs.com/package/object-assign).  Upgrading node is probably a better choice because there's a chance you'll run into other problem with such an old version.

**Comment by ksgithubapp** [comment]
its v6.11.3

**Comment by raaajit** [comment]
Hi,

I'm also having the same issue,

TypeError: Object function Object() { [native code] } has no method 'assign'.

My Node Version is -> v0.10.25
O/S -> Ubuntu 14.04

I tried everything but still unable ti resolve.

Could someone please help me to solve this.

**Comment by P110** [comment]
Hi,
for anyone having this issue in the future, you need to update your node version, you can try to do this with the commands shown here (at time of writing).

https://stackoverflow.com/questions/23940172/not-seeing-latest-version-when-updating-node-js-via-installer-msi-windows-7

May not work for you but it worked for me.
