### ISSUE TITLE
Server does not run on NodeJS 5.8

### ISSUE THREAD

**Issue by vemacs** [typpo/textbelt#75]
```
node server/app.js
textbelt/lib/carriers.js:30
  nex-tech: [
     ^

SyntaxError: Unexpected token -
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (textbelt/server/app.js:4:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by typpo** [comment]
Thanks for catching this!

**Comment by vemacs** [comment]
:+1:
