### ISSUE TITLE
curl: (52) Empty reply from server

### ISSUE THREAD

**Issue by akshayvyas29** [typpo/textbelt#80]
I have setup textbelt as stanalone server, redis server is running and properly and when i start the server its starting without any errors but when i try to send the message through server i am getting "curl: (52) Empty reply from server" post that the server process terminates with exit 1

```
root@ssdnodes-763224:/usr/share/nginx/textbelt-master# curl -X POST http://66.11.122.204:9090/text    -d number=<number>    -d "message=I sent this message for free with textbelt.com"
curl: (52) Empty reply from server
[1]+  Exit 1                  nohup node server/app.js

```

**Comment by akshayvyas29** [comment]
I am getting the following error

```
output('mutt failed', {email: email, data: decoder.write(data)});
                                  ^

ReferenceError: email is not defined
    at ChildProcess.<anonymous> (/usr/share/nginx/textbelt-master/lib/text.js:76:35)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

```

**Comment by typpo** [comment]
Hi Akshay,

I just committed 3d758729e58a5f2467ce6fbfecfab94b2f6bfd0f to fix this particular crash in the error handler.  Although it fixes the crash, it won't fix the fact that mutt failed.

Do you have `mutt` installed on the server?  I should update the README to explain the `mutt` dependency.

**Comment by akshayvyas29** [comment]
Hi Ian

I made a new clone and installed mull now i don't see any error but curl stalls for a min and sends the same error

```
root@ssdnodes-763224:~# curl -X POST http://66.11.122.204:9090/text \
>    -d number=702XXXXX \
>    -d "message=I sent this message for free with textbelt.com"
curl: (52) Empty reply from server
```
```
root@ssdnodes-763224:~/textbelt# node server/app.js
1 'banned ips loaded'
Listening on 9090
txting phone 7023XXXXXX : I sent this message for free with textbelt.com
I sent this message for free with textbelt.com
```
