### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined (of providers_list)

### ISSUE THREAD

**Issue by pgibler** [typpo/textbelt#97]
Server now starts and it listens on port 9090, but now it fails on line 43 of text.js:

```
/opt/textbelt/textbelt-master/lib/text.js:43
  var emails = providers_list.map(function(provider) {
                             ^

TypeError: Cannot read property 'map' of undefined
    at Object.sendText [as send] (/opt/textbelt/textbelt-master/lib/text.js:43:30)
    at doSendText (/opt/textbelt/textbelt-master/server/app.js:168:10)
    at Command.callback (/opt/textbelt/textbelt-master/server/app.js:242:7)
    at normal_reply (/opt/textbelt/textbelt-master/node_modules/redis/index.js:714:21)
    at RedisClient.return_reply (/opt/textbelt/textbelt-master/node_modules/redis/index.js:816:9)
    at JavascriptRedisParser.returnReply (/opt/textbelt/textbelt-master/node_modules/redis/index.js:188:18)
    at JavascriptRedisParser.execute (/opt/textbelt/textbelt-master/node_modules/redis-parser/lib/parser.js:491:12)
    at Socket.<anonymous> (/opt/textbelt/textbelt-master/node_modules/redis/index.js:267:27)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)

```

**Comment by typpo** [comment]
Oops.  Give it another shot - this time I tested the standalone server all the way through.  Thanks for catching this (I guess most people don't run it standalone)

**Comment by pgibler** [comment]
The server runs and is now returning "success" status in requests. It runs!
